---
version: '2'
services:
  # django app
  europe-api:
    container_name: api
    image: msgre/common:europe-api.latest
    volumes:
      - $PWD/europe:/src/api 
    ports:
      - "8080:8080"
    command: --socket 0.0.0.0:8080 --master --processes 1 --max-requests 1 --env DJANGO_SETTINGS_MODULE=europe.settings --module europe.wsgi:application --chdir /src/api
    stop_signal: SIGINT

  # javascript application
  europe-js:
    container_name: js
    image: msgre/common:europe-js.latest 
    command: /bin/true
    volumes:
      - $PWD/static:/src/js 

  # watcher application (websocket bridge between browser and HW)
  europe-watcher:
    container_name: watcher
    image: msgre/common:europe-watcher.latest 
    volumes:
      - $PWD/watcher/gates:/root/gates 
    ports:
      - "8082:8082"
    environment:
      DEBUG: 1
    tty: true

  # nginx proxy
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - "$PWD/ansible/files/europe.nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "8081:80"
    volumes_from:
      - europe-js
    links:
      - europe-api
      - europe-watcher
