---
version: '2'
services:
  # watcher application (websocket bridge between browser and HW)
  watcher:
    environment:
      DEBUG: 1

  # share folder with content, for easier game initialization
  admin:
    volumes:
      - $PWD/content:/content
